<a href="https://colab.research.google.com/github/Prayush77/AI_Foundation/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random
# set random seed fro reproductibility
np.random.seed(42)

# generate data
num_rows = 100
data = {
    'user ID':range(1,num_rows+1),
    'Gender': [random.choice(['Male','Female']) for _ in range(num_rows)],
    'Age':[random.randint(18,65) for _ in range(num_rows)],
    'Estimated Salary' : np.random.randint(20000 ,200000,num_rows),
    'Purchased':np.random.randint(0,2,num_rows)
    }

# create dataframe
df = pd.DataFrame(data)
df.to_csv('dataset.csv', index=False)



In [ ]:
# import the dataset
df=pd.read_csv('dataset.csv')
df.head(5)

user ID  Gender  Age  Estimated Salary  Purchased
0        1  Female   31            141958          0
1        2  Female   24            166867          0
2        3    Male   29            151932          1
3        4    Male   20            123694          0
4        5    Male   63            139879          1

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv')
df.head(5)

user ID  Gender  Age  Estimated Salary  Purchased
0        1  Female   31            141958          0
1        2  Female   24            166867          0
2        3    Male   29            151932          1
3        4    Male   20            123694          0
4        5    Male   63            139879          1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset =pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv')

In [ ]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values

In [ ]:
display(x)

array([[    31, 141958],
       [    24, 166867],
       [    29, 151932],
       [    20, 123694],
       [    63, 139879],
       [    34, 130268],
       [    19,  74886],
       [    26, 157337],
       [    22, 188266],
       [    62, 107498],
       [    38, 132727],
       [    64, 146324],
       [    55, 195203],
       [    52,  36023],
       [    23,  61090],
       [    56,  87221],
       [    50,  84820],
       [    48,  20769],
       [    51,  79735],
       [    29,  84925],
       [    57,  25311],
       [    45, 123355],
       [    43, 105305],
       [    29, 179765],
       [    65, 150608],
       [    51, 176730],
       [    50, 104478],
       [    47, 142537],
       [    62, 169503],
       [    36, 150523],
       [    37,  22747],
       [    32, 143855],
       [    59,  85725],
       [    55, 149981],
       [    62, 104654],
       [    39, 186845],
       [    38, 139346],
       [    62,  87435],
       [    41,  76886],
       [    47,  86803],


In [ ]:
display(y)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
# splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
#

In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

In [ ]:
avg_salary = np.mean(dataset['Estimated Salary'])
print("Average Salary:", avg_salary)

Average Salary: 107118.92


In [ ]:
# fitting KNN classifier to the training test
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
# predictiong the results
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0])

Fitting K-NN classifier to the training data:Now we will fit the K-NN classifier to the trainig data.To do this we will import the KNieghborsClassifer class of Sklearn Neighbors library.After importing the class, we will create the Classifier object of the class.The Paramater of this class will be
    

n_neighbors: to define the required neighbours of the algorithm.Usually,it takes 5.

metric='minkowski':This is the default parameter and it decides the distance between the points

p=2:It is equivalent to the standard Euclidean metric


In [ ]:
dataset.describe()
dataset['Age'].mode()

0    62
Name: Age, dtype: int64

In [ ]:
avg_age = np.mean(dataset['Age'])
print("Average Age:", avg_age)

Average Age: 42.22


In [ ]:
dataset

user ID  Gender  Age  Estimated Salary  Purchased
0         1  Female   31            141958          0
1         2  Female   24            166867          0
2         3    Male   29            151932          1
3         4    Male   20            123694          0
4         5    Male   63            139879          1
..      ...     ...  ...               ...        ...
95       96  Female   52             59504          0
96       97  Female   27            184231          0
97       98    Male   24             33986          1
98       99    Male   39             81858          0
99      100  Female   54            149312          1

[100 rows x 5 columns]